version: '3'
services:
  solace:
    container_name: solace_rust
    image: solace/solace-pubsub-standard:9.0.1.7
    shm_size: 2g
    ulimits:
      core: 1
      nofile:
        soft: 418332
        hard: 418332
    ports:
      #SEMP / PubSub+ Manager
      - '8080:8080'
      #SMF
      - '55555:55555'
    environment:
      - username_admin_globalaccesslevel=admin
      - username_admin_password=admin
      - system_scaling_maxconnectioncount=100
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 2m00s
      timeout: 10s
      retries: 3

